# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _match
zstyle ':completion:*' completions 1
zstyle ':completion:*' expand suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format '%d'
zstyle ':completion:*' glob 1
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' substitute 1
zstyle :compinstall filename '/Users/danielge/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd
bindkey -e
# End of lines configured by zsh-newuser-install

# load zgen
source "${HOME}/bin/zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # oh-my-zsh plugins
    plugins=(brew extract git)
    for plugin in $plugins
    do
        zgen oh-my-zsh plugins/$plugin
    done
    zgen load zsh-users/zsh-syntax-highlighting

    zgen load rimraf/k

    # completions
    zgen load zsh-users/zsh-completions src

    # theme
    zgen load $HOME/.themes/danielge.zsh-theme

    zgen save
fi

source ~/bin/z.sh

# Start an HTTP server from a directory, optionally specifying the port
function server() {
    local port="${1:-8000}"
    ( sleep 2; open "http://localhost:${port}/" ) &
    python -m SimpleHTTPServer "$port"
}

source $HOME/.aliases

export GOPATH="$HOME/go"

# Customize to your needs...
PATH="/usr/local/bin:/usr/local/sbin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$PATH:$GOPATH/bin"

PATH="$PATH:$HOME/.cabal/bin"
export PATH=$PATH

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
