#######################################################
# bootstrap Square zshrc; please don't change this bit.
#######################################################
if [[ -d "$HOME/Development" ]]; then
  export SQUARE_HOME=$HOME/Development
fi
if [[ -f "$SQUARE_HOME/config_files/square/zshrc" ]]; then
  source $SQUARE_HOME/config_files/square/zshrc
fi

# Source universal zsh configuration
source "$HOME/dotfiles/dotfiles/zshrc"

# Square-specific setup
source "$SQUARE_HOME/config_files/zsh/history.zsh"
# This alias isn't useful outside of Square
alias gpr='gh pr create --web'

### Work-specific utilities ###

reset-wifi() {
    networksetup -setairportpower en0 off
    sleep 1
    networksetup -setairportpower en0 on
}

mkgif() {
    local input="$1"
    local tmpdir="$(mktemp -d -t palette)"
    local tmpfile="$tmpdir/palette.png"
    ffmpeg -i "$input" -vf palettegen "$tmpfile" &&
        (ffmpeg -i "$input" -i "$tmpfile" -lavfi paletteuse -f gif - | \
        gifsicle --optimize=3 --delay=3 --no-conserve-memory --output -)
}

# Pick a k8s pod
pick_pod() {
    kubectl get pods --no-headers -o custom-columns=":metadata.name" | head -n 1
}

### Work-specific PATH and tools ###

# PATH configuration
export PATH="$PATH:$HOME/Development/topsoil/bin"
export PATH="/usr/local/opt/python/libexec/bin:$PATH:$HOME/.cargo/bin"

# rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
[[ "$PATH" != *".rvm"* ]] && PATH=$PATH:$HOME/.rvm/bin

# nvm (with Square config)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export NODE_EXTRA_CA_CERTS=/opt/homebrew/etc/ca-certificates/cert.pem
export COREPACK_NPM_REGISTRY=https://global.block-artifacts.com/artifactory/api/npm/square-npm/
export COREPACK_INTEGRITY_KEYS=0

# Terraform completion
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C $(which terraform) terraform

# Docker Desktop completions
fpath=(/Users/dge/.docker/completions $fpath)
autoload -Uz compinit
compinit
